### ISSUE TITLE
Expo Prebuild type error effecting `expo-health-connect` plugin

### ISSUE THREAD

**Issue by seanblonien** [matinzd/expo-health-connect#3]
When switching over from the react-native-health-connect manual integration w/ Expo to use this expo plugin managed version of the package, when running `expo prebuild`, I get this following error:

```sh
npx expo prebuild        
env: load .env
env: export ...
✔ Created native directories | reusing /android, /ios
✔ Updated package.json | no changes
✖ Prebuild failed
TypeError: [android.manifest]: withAndroidManifestBaseMod: activityAliases.some is not a function
TypeError: [android.manifest]: withAndroidManifestBaseMod: activityAliases.some is not a function
    at hasActivityAlias (/.../git/fly-fit/node_modules/expo-health-connect/build/withHealthConnect.js:14:28)
    at /.../git/fly-fit/node_modules/expo-health-connect/build/withHealthConnect.js:54:14
```

I opened up the `withHealthConnect.js` and see the issue immediately when i log the `activityAliases` variable:

```js
// ...
// @ts-ignore - Expo does not have types for security-alias
const activityAliases = mainApplication["activity-alias"];
console.warn({activityAliases})
if (!hasActivityAlias("ViewPermissionUsageActivity", activityAliases)) {
// ...
```
logs
```js
{
  activityAliases: {
    '$': {
      'android:name': 'AndroidURationaleActivity',
      'android:exported': 'true',
      'android:targetActivity': '.MainActivity',
      'android:permission': 'android.permission.START_VIEW_PERMISSION_USAGE'
    },
    'intent-filter': { action: [Object], category: [Object] }
  }
}
```

and it seems like `hasActivityAlias` function assumes `activityAliases` is an array, but it is in fact an object/record type, therefore it gets the type error.

this is the order of my expo plugins (unsure if the order could be the issue):
```js
plugins: [
    [
      'expo-build-properties',
      {
        ios: {
          useFrameworks: 'static',
          newArchEnabled: true,
          ccacheEnabled: true,
        },
        android: {
          compileSdkVersion: 34,
          targetSdkVersion: 34,
          buildToolsVersion: '34.0.0',
          minSdkVersion: 26,
          newArchEnabled: true,
        },
      },
    ],
    'expo-health-connect',
    'expo-asset',
    'expo-localization',
    [
      'expo-font',
      { ... },
    ],
    [
      'expo-image-picker',
      { ... },
    ],
    'react-native-email-link',
    'react-native-health',
    './scripts/plugins/android-manifest-plugins.cjs',
  ],
```

versions:
expo@51.0.36
react-native@0.74.5
react-native-health-connect@3.1.1
expo-health-connect@0.1.1

**Comment by matinzd** [comment]
Hey!

 Can you also share the generated AndroidManifest before adding the plugin? This used to be an array. I feel like there has been some breaking changes that I am not aware of.

**Comment by seanblonien** [comment]
My bad, my own expo plugin at that path of `./scripts/plugins/android-manifest-plugins.cjs` changed the type from an array to an object... whoops. so fixing that bug in that custom plugin it ran successfully 👍
